"""
Unit tests for models.py — the behavioural methods on each model
(predicates, to_dict shapes, expiry logic, computed counts/waits).

Persistence is exercised through the in-memory SQLite bound by BaseBackendTest,
but most assertions target pure Python behaviour on the model objects.
"""
from datetime import datetime, timedelta, timezone, date

from tests.base import BaseBackendTest
from models import (
    User, PendingRegistration, ResetCode, Service, Admin, Queue, Ticket,
    InviteToken, ServiceSchedule, Notification, DeviceToken, SwapRequest,
)


class TestUserModel(BaseBackendTest):
    def test_role_predicates(self):
        client = self.make_user(role="client")
        self.assertTrue(client.is_client())
        self.assertFalse(client.is_admin())

    def test_mark_verified_flips_flag(self):
        user = self.make_user(verified=False)
        self.assertFalse(user.is_verified())
        user.mark_verified()
        self.assertTrue(user.is_verified())

    def test_to_dict_shape_and_string_ids(self):
        user = self.make_user(username="bob", email="bob@x.com", role="admin")
        d = user.to_dict()
        self.assertEqual(
            set(d), {"user_id", "username", "email", "role"}
        )
        self.assertEqual(d["user_id"], str(user.id))
        self.assertEqual(d["role"], "admin")


class TestPendingRegistrationModel(BaseBackendTest):
    def _make_pending(self, expire_at):
        rec = PendingRegistration(
            username="alice", email="a@x.com", hashed_password=b"h",
            role="client", code="123456", expire_at=expire_at,
        )
        self.db.session.add(rec)
        self.db.session.commit()
        return rec

    def test_is_expired_true_in_past(self):
        rec = self._make_pending(datetime.utcnow() - timedelta(minutes=1))
        self.assertTrue(rec.is_expired())

    def test_is_expired_false_in_future(self):
        rec = self._make_pending(datetime.utcnow() + timedelta(minutes=10))
        self.assertFalse(rec.is_expired())

    def test_update_code_replaces_code_and_expiry(self):
        rec = self._make_pending(datetime.utcnow() + timedelta(minutes=10))
        new_exp = datetime.utcnow() + timedelta(minutes=30)
        rec.update_code("654321", new_exp)
        self.assertEqual(rec.code, "654321")
        self.assertEqual(rec.expire_at, new_exp)

    def test_to_user_payload_carries_credentials(self):
        rec = self._make_pending(datetime.utcnow() + timedelta(minutes=10))
        payload = rec.to_user_payload()
        self.assertEqual(payload["email"], "a@x.com")
        self.assertEqual(payload["hashed_password"], b"h")


class TestResetCodeModel(BaseBackendTest):
    def test_is_expired_and_update(self):
        rec = ResetCode(email="a@x.com", code="111111",
                        expire_at=datetime.utcnow() - timedelta(seconds=1))
        self.db.session.add(rec)
        self.db.session.commit()
        self.assertTrue(rec.is_expired())
        future = datetime.utcnow() + timedelta(minutes=5)
        rec.update_code("222222", future)
        self.assertEqual(rec.code, "222222")
        self.assertFalse(rec.is_expired())


class TestServiceModel(BaseBackendTest):
    def test_to_dict(self):
        svc = self.make_service(name="Clinic")
        d = svc.to_dict()
        self.assertEqual(d["service_name"], "Clinic")
        self.assertEqual(d["owner_id"], str(svc.owner_id))


class TestAdminModel(BaseBackendTest):
    def test_role_predicates(self):
        user = self.make_user()
        svc = self.make_service(owner=user)
        admin = Admin(user_id=user.id, service_id=svc.id, admin_role="boss")
        self.db.session.add(admin)
        self.db.session.commit()
        self.assertTrue(admin.is_boss())
        self.assertFalse(admin.is_manager())
        self.assertFalse(admin.is_agent())


class TestQueueModel(BaseBackendTest):
    def test_active_and_pending_counts(self):
        queue = self.make_queue()
        self.make_ticket(queue=queue, code="A1", status="active", position=0)
        self.make_ticket(queue=queue, code="A2", status="pending", position=1)
        self.make_ticket(queue=queue, code="A3", status="pending", position=2)
        self.assertEqual(queue.active_count(), 1)
        self.assertEqual(queue.pending_count(), 2)

    def test_to_dict_builds_join_url_from_base(self):
        queue = self.make_queue(name="Pharmacy", code="PHA")
        d = queue.to_dict(base_url="http://testhost")
        self.assertEqual(d["name"], "Pharmacy")
        self.assertTrue(d["join_url"].startswith("http://testhost/join/"))
        self.assertIn(queue.join_token, d["join_url"])

    def test_join_token_autogenerated_and_unique(self):
        q1 = self.make_queue(code="Q1")
        q2 = self.make_queue(service=q1.service, name="Other", code="Q2")
        self.assertIsNotNone(q1.join_token)
        self.assertNotEqual(q1.join_token, q2.join_token)


class TestTicketModel(BaseBackendTest):
    def test_status_predicates(self):
        t = self.make_ticket(status="active")
        self.assertTrue(t.is_active())
        self.assertFalse(t.is_pending())

    def test_actual_wait_minutes_computed(self):
        issued = datetime(2024, 1, 1, 10, 0, 0)
        called = datetime(2024, 1, 1, 10, 7, 0)
        t = self.make_ticket(issued_at=issued, called_at=called)
        self.assertEqual(t.actual_wait_minutes(), 7)

    def test_actual_wait_minutes_none_without_called_at(self):
        t = self.make_ticket(issued_at=datetime.utcnow(), called_at=None)
        self.assertIsNone(t.actual_wait_minutes())

    def test_actual_wait_never_negative(self):
        issued = datetime(2024, 1, 1, 10, 7, 0)
        called = datetime(2024, 1, 1, 10, 0, 0)  # called "before" issued
        t = self.make_ticket(issued_at=issued, called_at=called)
        self.assertEqual(t.actual_wait_minutes(), 0)

    def test_to_dict_serializes_datetimes_iso(self):
        t = self.make_ticket(code="GEN-009")
        d = t.to_dict()
        self.assertEqual(d["code"], "GEN-009")
        self.assertEqual(d["status"], "pending")
        self.assertIsInstance(d["issued_at"], str)  # isoformat
        self.assertIsNone(d["called_at"])


class TestInviteTokenModel(BaseBackendTest):
    def _invite(self, *, used=False, expires_in_hours=1):
        svc = self.make_service()
        inv = InviteToken(
            service_id=svc.id,
            admin_role="agent",
            used=used,
            expires_at=datetime.utcnow() + timedelta(hours=expires_in_hours),
        )
        self.db.session.add(inv)
        self.db.session.commit()
        return inv

    def test_valid_when_unused_and_unexpired(self):
        inv = self._invite(used=False, expires_in_hours=1)
        self.assertTrue(inv.is_valid())

    def test_invalid_when_expired(self):
        inv = self._invite(used=False, expires_in_hours=-1)
        self.assertTrue(inv.is_expired())
        self.assertFalse(inv.is_valid())

    def test_consume_marks_used_and_invalidates(self):
        inv = self._invite()
        inv.consume()
        self.assertTrue(inv.used)
        self.assertFalse(inv.is_valid())

    def test_to_dict_builds_invite_url(self):
        inv = self._invite()
        d = inv.to_dict(base_url="http://testhost")
        self.assertTrue(d["invite_url"].endswith(inv.token))


class TestServiceScheduleModel(BaseBackendTest):
    def test_to_dict_stringifies_times(self):
        sch = self.make_schedule(opening="09:00", closing="18:30", avg_duration=12)
        d = sch.to_dict()
        self.assertEqual(d["opening_time"], "09:00:00")
        self.assertEqual(d["closing_time"], "18:30:00")
        self.assertEqual(d["avg_duration"], 12)


class TestNotificationModel(BaseBackendTest):
    def test_to_dict_shape(self):
        svc = self.make_service()
        n = Notification(service_id=svc.id, type="queue_created",
                         title="Queue created: X", body="b", meta={"k": "v"})
        self.db.session.add(n)
        self.db.session.commit()
        d = n.to_dict()
        self.assertEqual(d["type"], "queue_created")
        self.assertEqual(d["meta"], {"k": "v"})
        self.assertFalse(d["read"])


class TestDeviceTokenModel(BaseBackendTest):
    def test_to_dict_omits_raw_token(self):
        user = self.make_user()
        dt = DeviceToken(user_id=user.id, token="fcm-abc-123", platform="android")
        self.db.session.add(dt)
        self.db.session.commit()
        d = dt.to_dict()
        self.assertEqual(d["platform"], "android")
        self.assertNotIn("token", d)  # raw FCM token must not be exposed


class TestSwapRequestModel(BaseBackendTest):
    def test_status_constants_and_predicates(self):
        self.assertEqual(SwapRequest.STATUS_PENDING, "pending")
        svc = self.make_service()
        q = self.make_queue(service=svc)
        t1 = self.make_ticket(queue=q, code="S1", position=1)
        t2 = self.make_ticket(queue=q, code="S2", position=2)
        swap = SwapRequest(service_id=svc.id,
                           requester_ticket_id=t1.id,
                           target_ticket_id=t2.id)
        self.db.session.add(swap)
        self.db.session.commit()
        self.assertTrue(swap.is_pending())
        self.assertFalse(swap.is_accepted())
        swap.status = SwapRequest.STATUS_ACCEPTED
        self.assertTrue(swap.is_accepted())

    def test_to_dict_shape(self):
        svc = self.make_service()
        q = self.make_queue(service=svc)
        t1 = self.make_ticket(queue=q, code="S1", position=1)
        t2 = self.make_ticket(queue=q, code="S2", position=2)
        swap = SwapRequest(service_id=svc.id,
                           requester_ticket_id=t1.id, target_ticket_id=t2.id)
        self.db.session.add(swap)
        self.db.session.commit()
        d = swap.to_dict()
        self.assertEqual(d["status"], "pending")
        self.assertEqual(d["requester_ticket_id"], str(t1.id))
        self.assertIsNone(d["responded_at"])
